// Central mock data for PickupContest

export const SITE_CONFIG_KEY = 'pickupcontest_config';

export const defaultConfig = {
  siteName: 'PickupContest',
  tagline: 'Find Your Next Challenge',
  logoText: 'PC',
  accentColor: '#F97316',
  primaryColor: '#2563EB',
  heroTitle: "Bangladesh's Premier Contest Platform for University Students",
  heroSubtitle: "Discover inter-university competitions, find teammates, and build your digital achievement portfolio.",
  contactEmail: 'hello@pickupcontest.com',
  socialLinks: {
    facebook: 'https://facebook.com/pickupcontest',
    twitter: 'https://twitter.com/pickupcontest',
    linkedin: 'https://linkedin.com/company/pickupcontest',
  },
  showBanner: true,
  bannerText: '🚀 New! National Hackathon 2026 registrations are open. Apply before June 1st!',
};

export const UNIVERSITIES = [
  { id: 'du', name: 'University of Dhaka', short: 'DU', type: 'public' },
  { id: 'buet', name: 'BUET', short: 'BUET', type: 'engineering' },
  { id: 'nsu', name: 'North South University', short: 'NSU', type: 'private' },
  { id: 'bracu', name: 'BRAC University', short: 'BRACU', type: 'private' },
  { id: 'iut', name: 'Islamic University of Technology', short: 'IUT', type: 'engineering' },
  { id: 'cu', name: 'University of Chittagong', short: 'CU', type: 'public' },
  { id: 'ru', name: 'University of Rajshahi', short: 'RU', type: 'public' },
  { id: 'aiub', name: 'American International University', short: 'AIUB', type: 'private' },
  { id: 'diu', name: 'Daffodil International University', short: 'DIU', type: 'private' },
  { id: 'sust', name: 'Shahjalal University', short: 'SUST', type: 'public' },
];

export const CATEGORIES = [
  { id: 'programming', name: 'Programming', icon: '💻', color: '#2563EB' },
  { id: 'business', name: 'Business Case', icon: '📊', color: '#F97316' },
  { id: 'robotics', name: 'Robotics', icon: '🤖', color: '#8B5CF6' },
  { id: 'debate', name: 'Debate', icon: '🎙️', color: '#10B981' },
  { id: 'art', name: 'Art & Design', icon: '🎨', color: '#EC4899' },
  { id: 'freelancing', name: 'Freelancing', icon: '🌐', color: '#F59E0B' },
  { id: 'science', name: 'Science Olympiad', icon: '🔬', color: '#06B6D4' },
  { id: 'math', name: 'Math Olympiad', icon: '📐', color: '#84CC16' },
];

export const initialContests = [
  {
    id: 1,
    title: 'IUPC 2026 — BUET National Programming Contest',
    organizer: 'BUET ACM Chapter',
    university: 'BUET',
    universityType: 'engineering',
    category: 'programming',
    prize: '৳ 1,50,000',
    prizeRaw: 150000,
    deadline: '2026-06-15',
    status: 'open',
    teamSize: '1–3',
    registered: 842,
    capacity: 1000,
    description: 'The annual BUET Inter-University Programming Contest — the most prestigious IUPC in Bangladesh. Open to all public, private, and engineering universities.',
    tags: ['IUPC', 'ACM', 'Competitive Programming'],
    isQuickPick: true,
    isNational: true,
    image: null,
    featured: true,
  },
  {
    id: 2,
    title: 'Hult Prize 2026 — Campus Round @ NSU',
    organizer: 'NSU Hult Prize Committee',
    university: 'NSU',
    universityType: 'private',
    category: 'business',
    prize: 'USD 1,000,000 (Global)',
    prizeRaw: 85000000,
    deadline: '2026-05-28',
    status: 'closing-soon',
    teamSize: '3–5',
    registered: 215,
    capacity: 300,
    description: 'Join the world\'s largest student competition. Solve social challenges through entrepreneurship. Campus winner advances to regionals.',
    tags: ['Social Impact', 'Startup', 'Entrepreneurship'],
    isQuickPick: true,
    isNational: false,
    image: null,
    featured: true,
  },
  {
    id: 3,
    title: 'National Robotics Championship 2026',
    organizer: 'IEEE Bangladesh Section',
    university: 'National',
    universityType: 'national',
    category: 'robotics',
    prize: '৳ 80,000',
    prizeRaw: 80000,
    deadline: '2026-07-01',
    status: 'open',
    teamSize: '2–4',
    registered: 178,
    capacity: 250,
    description: 'Annual national robotics championship open to all university students. Design, build and compete with autonomous robots.',
    tags: ['Robotics', 'Autonomous', 'IEEE'],
    isQuickPick: false,
    isNational: true,
    image: null,
    featured: false,
  },
  {
    id: 4,
    title: 'DU Inter-Faculty Debate Championship',
    organizer: 'DU Debate Circle',
    university: 'DU',
    universityType: 'public',
    category: 'debate',
    prize: '৳ 25,000',
    prizeRaw: 25000,
    deadline: '2026-05-20',
    status: 'closing-soon',
    teamSize: '2',
    registered: 64,
    capacity: 80,
    description: 'British Parliamentary debate format. Open to all DU departments. Judged by national-level debaters.',
    tags: ['Debate', 'BP Format', 'Public Speaking'],
    isQuickPick: false,
    isNational: false,
    image: null,
    featured: false,
  },
  {
    id: 5,
    title: 'National Innovation Hackathon — "Solve Bangladesh"',
    organizer: 'ICT Division, Bangladesh',
    university: 'National',
    universityType: 'national',
    category: 'programming',
    prize: '৳ 5,00,000',
    prizeRaw: 500000,
    deadline: '2026-06-10',
    status: 'open',
    teamSize: '3–5',
    registered: 1240,
    capacity: 2000,
    description: 'Government-backed hackathon to solve real-world Bangladeshi problems with technology. 48-hour intensive coding sprint.',
    tags: ['Hackathon', 'GovTech', 'Innovation'],
    isQuickPick: true,
    isNational: true,
    image: null,
    featured: true,
  },
  {
    id: 6,
    title: 'BRACU Design & Innovation Fest 2026',
    organizer: 'BRACU Art & Design Club',
    university: 'BRACU',
    universityType: 'private',
    category: 'art',
    prize: '৳ 40,000',
    prizeRaw: 40000,
    deadline: '2026-06-20',
    status: 'open',
    teamSize: '1–2',
    registered: 92,
    capacity: 200,
    description: 'Annual design competition covering UI/UX, graphic design, photography, and digital art. Open to all private university students.',
    tags: ['Design', 'UI/UX', 'Creative'],
    isQuickPick: false,
    isNational: false,
    image: null,
    featured: false,
  },
  {
    id: 7,
    title: 'CU Freelancing Championship 2026',
    organizer: 'CU IT Society',
    university: 'CU',
    universityType: 'public',
    category: 'freelancing',
    prize: '৳ 30,000',
    prizeRaw: 30000,
    deadline: '2026-07-15',
    status: 'open',
    teamSize: '1',
    registered: 320,
    capacity: 500,
    description: 'Showcase your freelancing skills — web dev, graphic design, content writing, and digital marketing. Bangladesh-wide competition.',
    tags: ['Freelancing', 'Remote Work', 'Skills'],
    isQuickPick: false,
    isNational: false,
    image: null,
    featured: false,
  },
  {
    id: 8,
    title: 'SUST Math Olympiad 2026',
    organizer: 'SUST Math Club',
    university: 'SUST',
    universityType: 'public',
    category: 'math',
    prize: '৳ 15,000',
    prizeRaw: 15000,
    deadline: '2026-05-15',
    status: 'results-out',
    teamSize: '1',
    registered: 430,
    capacity: 500,
    description: 'Annual mathematics competition for university students. Tests advanced problem solving, combinatorics, and number theory.',
    tags: ['Math', 'Olympiad', 'Problem Solving'],
    isQuickPick: false,
    isNational: false,
    image: null,
    featured: false,
  },
];

export const initialTeamPosts = [
  {
    id: 1,
    userId: 'user_1',
    name: 'Rafi Ahmed',
    university: 'BUET',
    avatar: 'RA',
    contest: 'IUPC 2026 — BUET',
    contestId: 1,
    lookingFor: ['Frontend Developer', 'Algorithm Expert'],
    skills: ['Python', 'Competitive Programming', 'C++'],
    message: 'Strong CP background, need a teammate for IUPC. I specialize in graph theory & DP. Looking for someone with data structures experience.',
    postedAt: '2026-05-08',
    requests: 3,
  },
  {
    id: 2,
    userId: 'user_2',
    name: 'Nusrat Jahan',
    university: 'NSU',
    avatar: 'NJ',
    contest: 'Hult Prize 2026',
    contestId: 2,
    lookingFor: ['Business Analyst', 'UI Designer'],
    skills: ['Marketing', 'Startup', 'Research'],
    message: 'Have a solid social impact idea for Hult Prize. Need a business analyst and someone who can present well. Let\'s build something meaningful!',
    postedAt: '2026-05-07',
    requests: 7,
  },
  {
    id: 3,
    userId: 'user_3',
    name: 'Tanvir Hossain',
    university: 'BRACU',
    avatar: 'TH',
    contest: 'National Hackathon — Solve Bangladesh',
    contestId: 5,
    lookingFor: ['Backend Developer', 'ML Engineer', 'UI/UX Designer'],
    skills: ['React', 'Node.js', 'Project Management'],
    message: 'Building a healthcare access solution for rural Bangladesh. Have the frontend covered, need strong backend and ML folk urgently!',
    postedAt: '2026-05-06',
    requests: 12,
  },
  {
    id: 4,
    userId: 'user_4',
    name: 'Sumaiya Islam',
    university: 'DU',
    avatar: 'SI',
    contest: 'BRACU Design Fest 2026',
    contestId: 6,
    lookingFor: ['Graphic Designer'],
    skills: ['Figma', 'Illustration', 'Motion Design'],
    message: 'UI/UX designer looking for a graphic designer partner for the Design Fest. Strong portfolio, let\'s collaborate!',
    postedAt: '2026-05-09',
    requests: 2,
  },
];

export const initialUsers = [
  {
    id: 'user_admin',
    name: 'Admin User',
    email: 'admin@pickupcontest.com',
    password: 'admin123',
    role: 'admin',
    university: 'National',
    department: 'Platform',
    avatar: 'AU',
    bio: 'Platform Administrator',
    skills: ['Management'],
    badges: ['platform_admin'],
    participatedContests: [],
    wonContests: [],
    joinedAt: '2026-01-01',
  },
  {
    id: 'user_1',
    name: 'Rafi Ahmed',
    email: 'rafi@student.buet.ac.bd',
    password: 'password123',
    role: 'student',
    university: 'BUET',
    department: 'CSE',
    avatar: 'RA',
    bio: 'Competitive programmer | CSE @ BUET | 3x IUPC finalist',
    skills: ['C++', 'Python', 'Graph Theory', 'Dynamic Programming'],
    badges: ['top_coder', 'finalist_iupc_2025', 'hackathon_winner'],
    participatedContests: [1, 5],
    wonContests: [5],
    joinedAt: '2026-02-14',
  },
  {
    id: 'user_2',
    name: 'Nusrat Jahan',
    email: 'nusrat@northsouth.edu',
    password: 'password123',
    role: 'student',
    university: 'NSU',
    department: 'BBA',
    avatar: 'NJ',
    bio: 'Aspiring entrepreneur | Hult Prize Campus Director 2025 | Love social innovation',
    skills: ['Business Analysis', 'Marketing', 'Public Speaking', 'Research'],
    badges: ['campus_director', 'hult_finalist'],
    participatedContests: [2, 4],
    wonContests: [],
    joinedAt: '2026-01-20',
  },
];

export const BADGE_INFO = {
  top_coder: { label: 'Top Coder', color: '#2563EB', icon: '💻' },
  finalist_iupc_2025: { label: 'IUPC Finalist 2025', color: '#8B5CF6', icon: '🏆' },
  hackathon_winner: { label: 'Hackathon Winner', color: '#F97316', icon: '🥇' },
  campus_director: { label: 'Campus Director', color: '#10B981', icon: '🎯' },
  hult_finalist: { label: 'Hult Finalist', color: '#EC4899', icon: '🌟' },
  platform_admin: { label: 'Platform Admin', color: '#64748B', icon: '⚙️' },
  debate_champion: { label: 'Debate Champion', color: '#F59E0B', icon: '🎙️' },
  robotics_builder: { label: 'Robotics Builder', color: '#06B6D4', icon: '🤖' },
};
